### ISSUE TITLE
Potential EULA violation

### ISSUE THREAD

**Issue by fontpolice** [mladilav/backbone-handy#1]
Dear mladilav,

It has come to our attention through [FontFinder](http://www.fontfinder.io) that your hosting of OpenSans-Regular.woff in this _public_ repository could be a potential violation of the End User License Agreement (EULA) between yourself and the respective foundry.

We recommend that you [remove](https://github.com/blog/1545-deleting-files-on-github) the files to avoid further action.

Sincerely,
The Font Police

**Comment by codingisacopingstrategy** [comment]
Yo, @fontpolice you’ve now made issues at 5 repos that use Open Sans:

https://github.com/mladilav/backbone-handy/issues/1
https://github.com/mladilav/handyboy-css/issues/1
https://github.com/Jansbury/CrayonWebsite/issues/1
https://github.com/michaelschofield/asl-wp-theme-child-public/issues/1

It is perfectly fine to embed Open Sans in a repo. It is licensed under the Apache 2 license which permits, among other things, redistribution. It even comes bundled with Wordpress.

To the repo owner—
Feel free to ignore this message

I got a [similar message](https://github.com/osp/osp.workshop.write-me-a-shadow/issues/1), I think this is a feature of their website which allows people to automatically send these messages—or they’re doing automatic scanning themselves. Asked them about it but they didn’t reply…

**Comment by fontpolice** [comment]
We all make mistakes sometimes.
